[project]
name = "reproducible-research-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.0.2",
    "pandas>=2.2.3",
    "regex>=2024.11.6",
    "statistics>=1.0.3.5",
]
